In [110]:
import pandas as pd
import numpy as np

A = np.array([[2., -1, 3, 10],[1, 3, -2, 5],[4, 2, -3, 15]])
n = len(A)
print(n)
print(A)

for i in range(n-1):
    for p in range(i,n):
        if(A[p,i]==0):
            aux = A[p,:]
            A[p,:] = A[i,:]
            A[i,:] = aux
    for j in range(i+1,n):
        print(f'A[{j},{i}]={A[j,i]} e B[{i},{i}]={A[i,i]}')
        q = A[j,i]/A[i,i]
        A[j,:] = A[j,:] - q*A[i,:]
        print(A)

#if(A[n,n] == 0):
#    print("Não existe solução única")

#X = np.array([])

x = A[n-1,n]/A[n-1,n-1]
print(x)
X = np.array([0,0,x])
#X[0] = x
#X = np.insert(X, len(X), x)

for i in range(n):
    m = n - i - 1
    #soma = 0
    #for j in range(m+1, n):
    #    soma += A[m,j]* X[j]
    #    print(f'soma={soma}')
    #print(f'i={i}, m={m}, n={n}')
    #print(f'A[m,n] = {A[m,n]}, A[m,m] = {A[m,m]}')
    #X[m] = (A[m,n] - soma) / A[m,m]
    X[m] = (A[m][n] - sum(A[m][k] * X[k] for k in range(m+1, n))) / A[m][m]
    #X = np.insert(X, len(X), x)

print(X)
#(A[i,n+1] - SOMATORIO) / A[i,i]

3
[[ 2. -1.  3. 10.]
 [ 1.  3. -2.  5.]
 [ 4.  2. -3. 15.]]
A[1,0]=1.0 e B[0,0]=2.0
[[ 2.  -1.   3.  10. ]
 [ 0.   3.5 -3.5  0. ]
 [ 4.   2.  -3.  15. ]]
A[2,0]=4.0 e B[0,0]=2.0
[[ 2.  -1.   3.  10. ]
 [ 0.   3.5 -3.5  0. ]
 [ 0.   4.  -9.  -5. ]]
A[2,1]=4.0 e B[1,1]=3.5
[[ 2.  -1.   3.  10. ]
 [ 0.   3.5 -3.5  0. ]
 [ 0.   0.  -5.  -5. ]]
1.0
[4. 1. 1.]


In [13]:
E = np.array([[2.,-1,3, 10],[1,3,-2, 5],[4,2,-3,15]])
n = len(E)
E[n-1,n]

15.0

In [35]:
C = np.array([])
C = np.insert(C, len(C), 1)
C = np.insert(C, len(C), 2)
C = np.insert(C, len(C), 5)
C

array([1., 2., 5.])

In [100]:
D = np.array([[2.,-1,3],[1,3,-2],[4,2,-3]])
n = len(D)
D[n-1,n-1]

-3.0

In [106]:
b2 = sum(A[2][j] * X[j] for j in range(2+1, n))
print(b2)
b1 = sum(A[1][j] * X[j] for j in range(1+1, n))
print(b1)
b0 = sum(A[0][j] * X[j] for j in range(0+1, n))
print(b0)

0
-3.5
2.0


In [109]:
A = 0
n = 0
b = 0
i = 0
j = 0