<img src="https://i.imgur.com/olPPiRS.jpg" alt="Texto alternativo da imagem" style="float:left; margin-right:10px;" />

<h3 style="margin-left:150px; margin-right:10px;"> Instituto Federal de Educação, Ciência e Tecnologia de Minas Gerais
Campus Ibirité<h3>

<br></br>
* Autor: Pablo Teodoro Monteiro 
> Engenharia de Controle e Automação - IFMG
>> Cálculo Numérico
>>> Atividade 09

In [280]:
#1
import pandas as pd
import numpy as np
import math as m

def linearSolver(A):    # Algoritmo da CN08 com fato de balanceamento
    n = len(A)
    s = np.zeros(n)                                     # vetor dos fatores de balanço
    #---------------------------inicio pivotamento----------------------
    for i in range(n-1):
        a = np.zeros(n)                                 # vetor das razões dos fatores
            #-------------
        p = i
        while p<n and A[p,i]==0:
            p = p + 1
            if(p == n):
                return "NÃO EXISTE SOLUÇÃO ÚNICA A[p,i]=0"
            #-------------
        if p != i:
            aux = np.copy(A[p,:])
            A[p,:] = np.copy(A[i,:])
            A[i,:] = aux
            #-------------
        for l in range(i,n):
            if(i==0):                               # Condição para formular o s[i] uma unica vez
                s[l] = np.max(np.abs(A[l,:n]))
                if(s[l]==0):
                    return "NÃO EXISTE SOLUÇÃO s = 0"
            a[l] = np.abs(A[l,i])/s[l]
        #print(f's = {s}; a = {a}')

        P = np.argmax(a)
        #print(f'P = {P}')
        #print(A)
        #print(f'A[i]:{A[i,:]}, A[P]:{A[P,:]}')
        '''
        Optou-se por não se utilizar o seguinte método na troca de linhas:
        auxL = np.copy(A[P,:] / s[P]) #Divisão pelo maior valor fazendo o pivor ir ao valor unitário
        A[P,:] = np.copy(A[i,:])
        A[i,:] = np.copy(auxL)

        Isso porque após algumas validações constatei que não fazer essa 'divisão' diminuia o erro em alguma medida para sistemas mais simples.

        Em comparação:
         
         Ao resolver o sistema:

            [0., 8, 7, 3]
            [6., 5, 4, 2]
            [3., 2, 1, 1]

        array([ 3.70074342e-17,  6.66666667e-01, -3.33333333e-01]) => para método que reduz as linhas nas trocas
        array([-5.55111512e-17,  6.66666667e-01, -3.33333333e-01]) => mantém a escala das linhas nas trocas
        '''
        auxL = np.copy(A[P,:] / s[P])
        A[P,:] = np.copy(A[i,:])
        A[i,:] = np.copy(auxL)
        #print(f'A[i]:{A[i,:]}, A[P]:{A[P,:]}')
        for j in range(i+1,n):
            #print(f'A[{j},{i}]={A[j,i]} e B[{i},{i}]={A[i,i]}')    #-----------------------PRINT DE VERIFICAÇÃO DOS TESTES-------------------------------
            #print(f'q = {A[j,i]}/{A[i,i]} = {A[j,i]/A[i,i]}; j={j}, i={i}')
            q = A[j,i]/A[i,i]
            #print(f'A[j,:] = {A[j,:]} = {A[j,:]} - {q} * {A[i,:]}')
            A[j,:] = A[j,:] - q*A[i,:]
            #print(A[j,:])
        #print(A)                                               #-----------------------PRINT DE VERIFICAÇÃO DOS TESTES-------------------------------
    #---------------------------fim pivotamento--------------------------
    if(A[n-1][n-1]==0):
        return "NÃO EXISTE SOLUÇÃO ÚNICA após pivotamento"

    x = A[n-1,n]/A[n-1,n-1]     #primeiro coeficiente, ultima linha

    X = np.empty(n)             #cria um array tamanho n vazio para armazenar os resultados
    X[n-1] = x

    for i in range(n):
        m = n - i-1
        X[m] = (A[m][n] - sum(A[m][k] * X[k] for k in range(m+1, n))) / A[m][m]
    return X

In [277]:
#2

def arr(num): # função para arredondar numeros para 4 algarismos significativos
    algar = 4
    prec = -1 * int(m.log10(np.abs(num))) + algar
    num_arr = round(num, prec)
    return num_arr

#----------------------------------------------------------------COM TROCA DE LINHAS-----------------------------------------------------------------
def linearSolver_q2(A):    # Algoritmo da CN08
    n = len(A)
    s = np.zeros(n)                                     # vetor dos fatores de balanço
    #---------------------------inicio pivotamento----------------------
    for i in range(n-1):
        a = np.zeros(n)                                 # vetor das razões dos fatores
            #-------------
        p = i
        while p<n and A[p,i]==0:
            p = p + 1
            if(p == n):
                return "NÃO EXISTE SOLUÇÃO ÚNICA A[p,i]=0"
            #-------------
        if p != i:
            aux = np.copy(A[p,:])
            A[p,:] = np.copy(A[i,:])
            A[i,:] = aux
            #-------------
        for l in range(i,n):
            if(i==0):                               # Condição para formular o s[i] uma unica vez
                s[l] = arr(np.max(np.abs(A[l,:n])))
                if(s[l]==0):
                    return "NÃO EXISTE SOLUÇÃO s = 0"
            a[l] = arr(np.abs(A[l,i])/s[l])
        #print(f's = {s}; a = {a}')

        P = np.argmax(a)
        #print(f'P = {P}')
        #print(A)
        #print(f'A[i]:{A[i,:]}, A[P]:{A[P,:]}')
        auxL = np.copy(A[P,:])
        A[P,:] = np.copy(A[i,:])
        A[i,:] = np.copy(auxL)
        #print(f'A[i]:{A[i,:]}, A[P]:{A[P,:]}')
        for j in range(i+1,n):
            #print(f'A[{j},{i}]={A[j,i]} e B[{i},{i}]={A[i,i]}')    #-----------------------PRINT DE VERIFICAÇÃO DOS TESTES-------------------------------
            #print(f'q = {A[j,i]}/{A[i,i]} = {A[j,i]/A[i,i]}; j={j}, i={i}')
            q = arr(A[j,i]/A[i,i])
            #print(f'A[j,:] = {A[j,:]} = {A[j,:]} - {q} * {A[i,:]}')
            A[j,:] = A[j,:] - q*A[i,:]
            #print(A[j,:])
        #print(A)                                               #-----------------------PRINT DE VERIFICAÇÃO DOS TESTES-------------------------------
    #---------------------------fim pivotamento--------------------------
    if(A[n-1][n-1]==0):
        return "NÃO EXISTE SOLUÇÃO ÚNICA após pivotamento"

    x = arr(A[n-1,n]/A[n-1,n-1])     #primeiro coeficiente, ultima linha

    X = np.empty(n)             #cria um array tamanho n vazio para armazenar os resultados
    X[n-1] = x

    for i in range(n):
        m = n - i-1
        X[m] = (A[m][n] - sum(A[m][k] * X[k] for k in range(m+1, n))) / A[m][m]
    return X

#----------------------------------------------------------------SEM TROCA DE LINHAS-----------------------------------------------------------------
def linearSolver_q1(A):    # Algoritmo da CN08
    n = len(A)
    s = np.zeros(n)                                     # vetor dos fatores de balanço
    #---------------------------inicio pivotamento----------------------
    for i in range(n-1):
        a = np.zeros(n)                                 # vetor das razões dos fatores
            #-------------
        p = i
        while p<n and A[p,i]==0:
            p = p + 1
            if(p == n):
                return "NÃO EXISTE SOLUÇÃO ÚNICA A[p,i]=0"
            #-------------
#        if p != i:
#            aux = np.copy(A[p,:])
#            A[p,:] = np.copy(A[i,:])
#            A[i,:] = aux
            #-------------
#        for l in range(i,n):
#            if(i==0):                               # Condição para formular o s[i] uma unica vez
#                s[l] = arr(np.max(np.abs(A[l,:n])))
#                if(s[l]==0):
#                    return "NÃO EXISTE SOLUÇÃO s = 0"
#            a[l] = arr(np.abs(A[l,i])/s[l])
#        #print(f's = {s}; a = {a}')
#
#        P = np.argmax(a)
#        #print(f'P = {P}')
#        #print(A)
#        #print(f'A[i]:{A[i,:]}, A[P]:{A[P,:]}')
#        auxL = np.copy(A[P,:])
#        A[P,:] = np.copy(A[i,:])
#        A[i,:] = np.copy(auxL)
        #print(f'A[i]:{A[i,:]}, A[P]:{A[P,:]}')
        for j in range(i+1,n):
            #print(f'A[{j},{i}]={A[j,i]} e B[{i},{i}]={A[i,i]}')    #-----------------------PRINT DE VERIFICAÇÃO DOS TESTES-------------------------------
            #print(f'q = {A[j,i]}/{A[i,i]} = {A[j,i]/A[i,i]}; j={j}, i={i}')
            q = arr(A[j,i]/A[i,i])
            #print(f'A[j,:] = {A[j,:]} = {A[j,:]} - {q} * {A[i,:]}')
            A[j,:] = A[j,:] - q*A[i,:]
            #print(A[j,:])
        #print(A)                                               #-----------------------PRINT DE VERIFICAÇÃO DOS TESTES-------------------------------
    #---------------------------fim pivotamento--------------------------
    if(A[n-1][n-1]==0):
        return "NÃO EXISTE SOLUÇÃO ÚNICA após pivotamento"

    x = arr(A[n-1,n]/A[n-1,n-1])     #primeiro coeficiente, ultima linha

    X = np.empty(n)             #cria um array tamanho n vazio para armazenar os resultados
    X[n-1] = x

    for i in range(n):
        m = n - i-1
        X[m] = (A[m][n] - sum(A[m][k] * X[k] for k in range(m+1, n))) / A[m][m]
    return X

A = np.array([[0.003, 59.14, 59.17],
            [5.29, -6.13, 46.78]])

#linearSolver(A)print(f'Solução com mudança de linhas: \t{linearSolver_q2}')
print(f'Sistema: \n{A[:,:len(A)]} \nCom solução: \n{np.reshape((A[:,len(A):]), 2)}\n')
print(f'Solução sem mudança de linhas: \t{linearSolver_q1(A)}. Erro de: {10.00207931-10.0:.10} e {1-0.99999989:.10} respectivamente')
print(f'Solução com mudança de linhas: \t{linearSolver_q2(A)}. Erro de: {10.00189027-10.0:.10} e {1-0.9999999:.10} respectivamente')

print("\nNote-se que não foi possível arredondar os valores da ultima etapa (Passo 11) por conta de erros de \"domínio matemático\" na função de aproximação 'arr()' ")

Sistema: 
[[ 3.000e-03  5.914e+01]
 [ 5.290e+00 -6.130e+00]] 
Com solução: 
[59.17 46.78]

Solução sem mudança de linhas: 	[10.00207931  0.99999989]. Erro de: 0.00207931 e 1.1e-07 respectivamente
Solução com mudança de linhas: 	[10.00189027  0.9999999 ]. Erro de: 0.00189027 e 9.999999995e-08 respectivamente

Note-se que não foi possível arredondar os valores da ultima etapa (Passo 11) por conta de erros de "domínio matemático" na função de aproximação 'arr()' 


In [278]:
#3
A = np.array([[30, 591400, 591700],
              [5.29, -6.13, 46.78]])

def arr(num): # função para arredondar numeros para 4 algarismos significativos
    algar = 4
    prec = -1 * int(m.log10(np.abs(num))) + algar
    num_arr = round(num, prec)
    return num_arr

#----------------------------------------------------------------COM TROCA DE LINHAS E PIVOTAMENTO-----------------------------------------------------------------
def linearSolver_q2(A):    # Algoritmo da CN08
    n = len(A)
    s = np.zeros(n)                                     # vetor dos fatores de balanço
    #---------------------------inicio pivotamento----------------------
    for i in range(n-1):
        a = np.zeros(n)                                 # vetor das razões dos fatores
            #-------------
        p = i
        while p<n and A[p,i]==0:
            p = p + 1
            if(p == n):
                return "NÃO EXISTE SOLUÇÃO ÚNICA A[p,i]=0"
            #-------------
        if p != i:
            aux = np.copy(A[p,:])
            A[p,:] = np.copy(A[i,:])
            A[i,:] = aux
            #-------------
        for l in range(i,n):
            if(i==0):                               # Condição para formular o s[i] uma unica vez
                s[l] = arr(np.max(np.abs(A[l,:n])))
                if(s[l]==0):
                    return "NÃO EXISTE SOLUÇÃO s = 0"
            a[l] = arr(np.abs(A[l,i])/s[l])
        #print(f's = {s}; a = {a}')

        P = np.argmax(a)
        #print(f'P = {P}')
        #print(A)
        #print(f'A[i]:{A[i,:]}, A[P]:{A[P,:]}')
        auxL = np.copy(A[P,:] / s[P])
        A[P,:] = np.copy(A[i,:] / s[i])
        A[i,:] = np.copy(auxL)
        #print(f'A[i]:{A[i,:]}, A[P]:{A[P,:]}')
        for j in range(i+1,n):
            #print(f'A[{j},{i}]={A[j,i]} e B[{i},{i}]={A[i,i]}')    #-----------------------PRINT DE VERIFICAÇÃO DOS TESTES-------------------------------
            #print(f'q = {A[j,i]}/{A[i,i]} = {A[j,i]/A[i,i]}; j={j}, i={i}')
            q = arr(A[j,i]/A[i,i])
            #print(f'A[j,:] = {A[j,:]} = {A[j,:]} - {q} * {A[i,:]}')
            A[j,:] = A[j,:] - q*A[i,:]
            #print(A[j,:])
        #print(A)                                               #-----------------------PRINT DE VERIFICAÇÃO DOS TESTES-------------------------------
    #---------------------------fim pivotamento--------------------------
    if(A[n-1][n-1]==0):
        return "NÃO EXISTE SOLUÇÃO ÚNICA após pivotamento"

    x = arr(A[n-1,n]/A[n-1,n-1])     #primeiro coeficiente, ultima linha

    X = np.empty(n)             #cria um array tamanho n vazio para armazenar os resultados
    X[n-1] = x

    for i in range(n):
        m = n - i-1
        X[m] = (A[m][n] - sum(A[m][k] * X[k] for k in range(m+1, n))) / A[m][m]
    return X

#----------------------------------------------------------------SEM TROCA DE LINHAS-----------------------------------------------------------------
def linearSolver_q1(A):    # Algoritmo da CN08
    n = len(A)
    s = np.zeros(n)                                     # vetor dos fatores de balanço
    #---------------------------inicio pivotamento----------------------
    for i in range(n-1):
        a = np.zeros(n)                                 # vetor das razões dos fatores
            #-------------
        p = i
        while p<n and A[p,i]==0:
            p = p + 1
            if(p == n):
                return "NÃO EXISTE SOLUÇÃO ÚNICA A[p,i]=0"
            #-------------
        if p != i:
            aux = np.copy(A[p,:])
            A[p,:] = np.copy(A[i,:])
            A[i,:] = aux
            #-------------
#        for l in range(i,n):
#            if(i==0):                               # Condição para formular o s[i] uma unica vez
#                s[l] = arr(np.max(np.abs(A[l,:n])))
#                if(s[l]==0):
#                    return "NÃO EXISTE SOLUÇÃO s = 0"
#            a[l] = arr(np.abs(A[l,i])/s[l])
#        #print(f's = {s}; a = {a}')
#
#        P = np.argmax(a)
#        #print(f'P = {P}')
#        #print(A)
#        #print(f'A[i]:{A[i,:]}, A[P]:{A[P,:]}')
#        auxL = np.copy(A[P,:] / s[P])
#        A[P,:] = np.copy(A[i,:] / s[i])
#        A[i,:] = np.copy(auxL)
        #print(f'A[i]:{A[i,:]}, A[P]:{A[P,:]}')
        for j in range(i+1,n):
            #print(f'A[{j},{i}]={A[j,i]} e B[{i},{i}]={A[i,i]}')    #-----------------------PRINT DE VERIFICAÇÃO DOS TESTES-------------------------------
            #print(f'q = {A[j,i]}/{A[i,i]} = {A[j,i]/A[i,i]}; j={j}, i={i}')
            q = arr(A[j,i]/A[i,i])
            #print(f'A[j,:] = {A[j,:]} = {A[j,:]} - {q} * {A[i,:]}')
            A[j,:] = A[j,:] - q*A[i,:]
            #print(A[j,:])
        #print(A)                                               #-----------------------PRINT DE VERIFICAÇÃO DOS TESTES-------------------------------
    #---------------------------fim pivotamento--------------------------
    if(A[n-1][n-1]==0):
        return "NÃO EXISTE SOLUÇÃO ÚNICA após pivotamento"

    x = arr(A[n-1,n]/A[n-1,n-1])     #primeiro coeficiente, ultima linha

    X = np.empty(n)             #cria um array tamanho n vazio para armazenar os resultados
    X[n-1] = x

    for i in range(n):
        m = n - i-1
        X[m] = (A[m][n] - sum(A[m][k] * X[k] for k in range(m+1, n))) / A[m][m]
    return X

#linearSolver(A)print(f'Solução com mudança de linhas: \t{linearSolver_q2}')
print(f'Sistema: \n{A[:,:len(A)]} \nCom solução: \n{np.reshape((A[:,len(A):]), 2)}\n')
print(f'Solução sem fator de escala: \t{linearSolver_q1(A)}. Erro de: {10.00207931-10.0:.10} e {1-0.99999989:.10} respectivamente')
print(f'Solução com fator de escala: \t{linearSolver_q2(A)}. Erro de: {10.00189027-10.0:.10} e {1-0.9999999:.10} respectivamente')

print("\nNote-se que não foi possível arredondar os valores da ultima etapa (Passo 11) por conta de erros de \"domínio matemático\" na função de aproximação 'arr()'.")

Sistema: 
[[ 3.000e+01  5.914e+05]
 [ 5.290e+00 -6.130e+00]] 
Com solução: 
[5.917e+05 4.678e+01]

Solução sem fator de escala: 	[10.00378121  0.99999981]. Erro de: 0.00207931 e 1.1e-07 respectivamente
Solução com fator de escala: 	[10.00189028  0.9999999 ]. Erro de: 0.00189027 e 9.999999995e-08 respectivamente

Note-se que não foi possível arredondar os valores da ultima etapa (Passo 11) por conta de erros de "domínio matemático" na função de aproximação 'arr()'.


In [279]:
#4
results = []
A = [[[58.9, 0.03, 59.3],
    [-6.1, 5.31, 47]],
    # SOLUÇÃO REAL: [1.0, 10.0]
    # SOLUÇÃO CODE: [ 1.0016968 , 10.00194924]
    [[3.333, 15920, -10.333, 7953],
    [2.222, 16.71, 9.612, 0.965],
    [-1.5611, 5.1791, 1.6852, 2.714]],
    # SOLUÇÃO REAL: [1, 0.5, -1]
    # SOLUÇÃO CODE: [-0.72877859,  0.49932397, -0.5991841 ]
    [[2.12, -2.12, 51.3, 100, m.pi],
    [0.333, -0.333, -12.2, -19.7, m.sqrt(2)],
    [6.19, 8.20, -1.00, -2.01, 0],
    [-5.73, 6.12, -1, -1, -1]],
    # SOLUÇÃO REAL: [0.0998, -0.0683, -0.0363, 0.0456]
    # SOLUÇÃO CODE: [ 0.14154452, -0.09702643, -0.88544172,  0.48058982]
    [[m.pi, m.sqrt(2), -1, 1, 0],
    [2.71828, -1, 1, 2, 1],
    [1, 1, -m.sqrt(3), 1, 2],
    [-1, -1, 1, -m.sqrt(5), 3]]]
            # SOLUÇÃO REAL: [1.35, -4.68, -4.03, -1.66]
            # SOLUÇÃO CODE: [ 1.34944895, -4.67798908, -4.03289418, -1.6566375 ]
for i in range(len(A)):
    print(f'Sistema:{i+1} \n{np.array(A[i])[:,:len(A[i])]} \nCom solução: \n{np.reshape((np.array(A[i])[:,len(A[i]):]), (len(A[i])))}\n')
    results.append(linearSolver(np.array(A[i])))
#print(f'Sistema: \n{A[:,:len(A)]} \nCom solução: \n{np.reshape((A[:,len(A):]), (len(A)))}\n')
print(A[1])
results

Sistema:1 
[[ 5.89e+01  3.00e-02]
 [-6.10e+00  5.31e+00]] 
Com solução: 
[59.3 47. ]

Sistema:2 
[[ 3.3330e+00  1.5920e+04 -1.0333e+01]
 [ 2.2220e+00  1.6710e+01  9.6120e+00]
 [-1.5611e+00  5.1791e+00  1.6852e+00]] 
Com solução: 
[7.953e+03 9.650e-01 2.714e+00]

Sistema:3 
[[  2.12   -2.12   51.3   100.   ]
 [  0.333  -0.333 -12.2   -19.7  ]
 [  6.19    8.2    -1.     -2.01 ]
 [ -5.73    6.12   -1.     -1.   ]] 
Com solução: 
[ 3.14159265  1.41421356  0.         -1.        ]

Sistema:4 
[[ 3.14159265  1.41421356 -1.          1.        ]
 [ 2.71828    -1.          1.          2.        ]
 [ 1.          1.         -1.73205081  1.        ]
 [-1.         -1.          1.         -2.23606798]] 
Com solução: 
[0. 1. 2. 3.]

[[3.333, 15920, -10.333, 7953], [2.222, 16.71, 9.612, 0.965], [-1.5611, 5.1791, 1.6852, 2.714]]


[array([ 1.0016968 , 10.00194924]),
 array([-0.72877859,  0.49932397, -0.5991841 ]),
 array([ 0.14154452, -0.09702643, -0.88544172,  0.48058982]),
 array([ 1.34944895, -4.67798908, -4.03289418, -1.6566375 ])]

In [281]:
# Matrix para testes
A = np.array([[0., 8, 7, 3],
              [6, 5, 4, 2],
              [3, 2, 1, 1]])
linearSolver(A)

array([-5.55111512e-17,  6.66666667e-01, -3.33333333e-01])

In [275]:
# Matrix para testes
A = np.array([[0, 0, -381.7, 2, -614.7751463810887],
              [1, -2.4, 150, -500, -467.78396660877524],
              [11234, 0, 1, 0, 35294.269904416484],
              [0, -2.7, 0, 3.14, -2.898730350987903]])
linearSolver(A)

array([3.14159265, 2.71828183, 1.61803399, 1.41421356])