In [5]:
#1
import pandas as pd
import numpy as np

def linearSolver(A):
    n = len(A)
    #---------------------------inicio pivotamento----------------------
    for i in range(n-1):
            #-------------
        p = i
        #for q in range(n):
        #    if(abs(A[q,p]) >= abs(A[0,p])):
        #        Aux = A[0,:]
        #        A[0,:] = A[q,:]
        #        A[q,:] = Aux

        while p<n and A[p,i]==0:
            p = p + 1
            if(p == n):
                return "NÃO EXISTE SOLUÇÃO ÚNICA"
            #-------------
        if p != i:
            aux = A[p,:]
            A[p,:] = A[i,:]
            A[i,:] = aux
            #-------------
        for j in range(i+1,n):
            #print(f'A[{j},{i}]={A[j,i]} e B[{i},{i}]={A[i,i]}')    #-----------------------PRINT DE VERIFICAÇÃO DOS TESTES-------------------------------
            q = A[j,i]/A[i,i]
            A[j,:] = A[j,:] - q*A[i,:]
            #print(A)                                               #-----------------------PRINT DE VERIFICAÇÃO DOS TESTES-------------------------------
    #---------------------------fim pivotamento--------------------------
    if(A[n-1][n-1]==0):
        return "NÃO EXISTE SOLUÇÃO ÚNICA"

    x = A[n-1,n]/A[n-1,n-1]     #primeiro coeficiente, ultima linha

    X = np.empty(n)             #cria um array tamanho n vazio para armazenar os resultados
    X[n-1] = x

    for i in range(n):
        m = n - i-1
        X[m] = (A[m][n] - sum(A[m][k] * X[k] for k in range(m+1, n))) / A[m][m]
    return X

In [6]:
#3
a = np.array([[(1/4), (1/5), (1/6), 9], [(1/3), (1/4), (1/5), 8], [(1/2), 1, 2, 8]])
b = np.array([[3.333, 15.920, -10.333, 15.913], [2.222, 16.71, 9.612, 28.544], [1.5611, 5.1791, 1.6852, 8.4254]])
c = np.array([[(1), (1/2), (1/3), (1/4), (1/6)], [(1/2), (1/3), (1/4), (1/5), (1/7)], [(1/3), (1/4), (1/5), (1/6), (1/8)], [(1/4), (1/5), (1/6), (1/7), (1/9)]])
d = np.array([[2., 1, -1, 1, -3, 7],[1, 0, 2, -1, 1, 2], [0, -2, -1, 1, -1, -5], [3, 1, -4, 0, 5, 6], [1, -1, -1, -1, 1, 3]])
Matrizes = [a, b, c, d]

for matrix in Matrizes:
    result = linearSolver(matrix)
    print(result)

#a) [-226.61538462  475.38461538 -176.53846154]
#b) [1.67672037 1.09211074 0.68343288]
#c) [ -140.03174603  1680.5952381  -4202.38095238  2802.77777778]
#d) [  7.5 -10.5   2.5   8.    1. ]

[-227.07692308  476.92307692 -177.69230769]
[0.41358627 1.30540797 0.60462382]
[-0.03174603  0.5952381  -2.38095238  2.77777778]
[ 1.91812865  1.96491228 -0.98830409 -3.19298246 -1.13450292]
