<img src="https://i.imgur.com/olPPiRS.jpg" alt="Texto alternativo da imagem" style="float:left; margin-right:10px;" />

<h3 style="margin-left:150px; margin-right:10px;"> Instituto Federal de Educação, Ciência e Tecnologia de Minas Gerais
Campus Ibirité<h3>

<br></br>
* Autor: Pablo Teodoro Monteiro 
> Engenharia de Controle e Automação - IFMG
>> Cálculo Numérico
>>> Atividade 10

In [60]:
#1
import math as m
import numpy as np
import pandas as pd

In [61]:
# 1
#  Jacobi
def jacobi(matrix, b, x0, tol, inter):
    n = len(matrix)
    x = np.array(x0)                    # inicializa x com valores iniciais
    x_new = np.zeros_like(x)            # cria novo array de zeros
    
    for k in range(inter):
        for i in range(n):
            soma = sum(matrix[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - soma) / matrix[i][i]
        
        diff = np.abs(x - x_new)   # Faz a diferença entre as matrizes
        residuo = matrix @ x - b
        if np.all(diff < tol):          # Checa a tolerancia
            return x, residuo
        
        x = x_new.copy()  # atualiza novos parametros
    
    return "Interação máxima. Solução não encontrada"

# Gauss Seidel
def gauss_seidel(matrix, b, x0, tol, inter):
    n = len(matrix)
    x = np.array(x0)                    # inicializa x com valores iniciais
    x_new = np.zeros_like(x)            # cria novo array de zeros

    for k in range(inter):
        for i in range(n):
            soma1 = sum(matrix[i][j] * x[j] for j in range(i))
            soma2 = sum(matrix[i][j] * x[j] for j in range(i+1, n))
            x_new[i] = (b[i] - soma1 - soma2) / matrix[i][i]
        
        diff = np.abs(x - x_new)            # Faz a diferença entre as matrizes
        residuo = matrix @ x - b
        if np.all(diff < tol):                  
            return x, residuo

        x = x_new.copy()                   # Armazena novos valores em X
    
    return "Interação máxima. Solução não encontrada"

In [62]:
#2

A = np.array([[1., -1, 1],[3, 6, 2],[3, 3, 7]])
a = np.array([1., 0, 4])

B = np.array([[10., -1, 0],[-1, 10, -2],[0, -2, 10]])
b = np.array([9., 7, 6])

C = np.array([[10., 5, 0, 0],[5, 10, -4, 0],[0, -4, 8, -1],[0, 0, -1, 5]])
c = np.array([6., 25, -11, -11])

D = np.array([[4., 1, 1, 0, 1],[-1, -3, 2, 1, 0],[2, 1, 5, -1, -1],[-1, -1, -1, 4, 0],[0, 2, -1, 1, 4]])
d = np.array([6., 6, 6, 6, 6])

tol = 10e-3
inter = 100

matrices = [A, B, C, D]
terms = [a, b, c, d]

for i in range(4):
    x0 = np.zeros(len(matrices[i]))
    sJ,resJ = jacobi(matrices[i], terms[i], x0, tol, inter) #s -> solução res -> residuo proposto no enunciado 3
    sGS,resGS = gauss_seidel(matrices[i], terms[i], x0, tol, inter) #s -> solução res -> residuo proposto no enunciado 3
    print(f'{matrices[i]}\n{terms[i]}\n Solução Jacobi: {sJ}\n Solução Gauss Seidel: {sGS}')

[[ 1. -1.  1.]
 [ 3.  6.  2.]
 [ 3.  3.  7.]]
[1. 0. 4.]
 Solução Jacobi: [ 0.0968173  -0.25619534  0.647803  ]
 Solução Gauss Seidel: [ 0.0968173  -0.25619534  0.647803  ]
[[10. -1.  0.]
 [-1. 10. -2.]
 [ 0. -2. 10.]]
[9. 7. 6.]
 Solução Jacobi: [0.9945 0.9555 0.789 ]
 Solução Gauss Seidel: [0.9945 0.9555 0.789 ]
[[10.  5.  0.  0.]
 [ 5. 10. -4.  0.]
 [ 0. -4.  8. -1.]
 [ 0.  0. -1.  5.]]
[  6.  25. -11. -11.]
 Solução Jacobi: [-0.79628579  2.78427779 -0.26026277 -2.25428875]
 Solução Gauss Seidel: [-0.79628579  2.78427779 -0.26026277 -2.25428875]
[[ 4.  1.  1.  0.  1.]
 [-1. -3.  2.  1.  0.]
 [ 2.  1.  5. -1. -1.]
 [-1. -1. -1.  4.  0.]
 [ 0.  2. -1.  1.  4.]]
[6. 6. 6. 6. 6.]
 Solução Jacobi: [ 0.77550283 -0.444489    1.70863536  2.00990049  1.64111383]
 Solução Gauss Seidel: [ 0.77550283 -0.444489    1.70863536  2.00990049  1.64111383]


In [72]:
#3
for i in range(4):
    x0 = np.zeros(len(matrices[i]))
    sJ,resJ = jacobi(matrices[i], terms[i], x0, tol, inter)
    sGS,resGS = gauss_seidel(matrices[i], terms[i], x0, tol, inter)
    print(f'{matrices[i]}\n{terms[i]}\n Solução Jacobi: {sJ}\n Resíduo: {resJ}\n\n Solução Gauss Seidel: {sGS}\n Resíduo: {resGS}\n')


[[ 1. -1.  1.]
 [ 3.  6.  2.]
 [ 3.  3.  7.]]
[1. 0. 4.]
 Solução Jacobi: [ 0.0968173  -0.25619534  0.647803  ]
 Resíduo: [0.00081563 0.04888588 0.05648688]

 Solução Gauss Seidel: [ 0.0968173  -0.25619534  0.647803  ]
 Resíduo: [0.00081563 0.04888588 0.05648688]

[[10. -1.  0.]
 [-1. 10. -2.]
 [ 0. -2. 10.]]
[9. 7. 6.]
 Solução Jacobi: [0.9945 0.9555 0.789 ]
 Resíduo: [-0.0105 -0.0175 -0.021 ]

 Solução Gauss Seidel: [0.9945 0.9555 0.789 ]
 Resíduo: [-0.0105 -0.0175 -0.021 ]

[[10.  5.  0.  0.]
 [ 5. 10. -4.  0.]
 [ 0. -4.  8. -1.]
 [ 0.  0. -1.  5.]]
[  6.  25. -11. -11.]
 Solução Jacobi: [-0.79628579  2.78427779 -0.26026277 -2.25428875]
 Resíduo: [-0.04146898 -0.09760001  0.03507544 -0.01118097]

 Solução Gauss Seidel: [-0.79628579  2.78427779 -0.26026277 -2.25428875]
 Resíduo: [-0.04146898 -0.09760001  0.03507544 -0.01118097]

[[ 4.  1.  1.  0.  1.]
 [-1. -3.  2.  1.  0.]
 [ 2.  1.  5. -1. -1.]
 [-1. -1. -1.  4.  0.]
 [ 0.  2. -1.  1.  4.]]
[6. 6. 6. 6. 6.]
 Solução Jacobi: [ 0.775